'use strict';

export const ERROR_CODES = {
  MERCHANT_INFO_REQUEST_ERROR: 'E_MERCHANT_INFO_REQUEST_ERROR',
  INVALID_CONFIG: 'E_INVALID_CONFIG',
  GOOGLE_PAY_INITIALIZATION_FAILED: 'E_GOOGLE_PAY_INITIALIZATION_FAILED',
};
//# sourceMappingURL=constants.js.map
